services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: stockdb
      MYSQL_USER: springuser
      MYSQL_PASSWORD: etshn-2025
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  spring-api:
    build: .
    container_name: spring-api
    restart: always
    depends_on:
      - mysql
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stockdb
      SPRING_DATASOURCE_USERNAME: springuser
      SPRING_DATASOURCE_PASSWORD: etshn-2025
      SPRING_JPA_HIBERNATE_DDL_AUTO: update

volumes:
  mysql_data:
