services:
  mysql:
    image: mysql:8
    container_name: mysql
    restart: always
    environment:
      MYSQL_DATABASE: stockdb
      MYSQL_ROOT_USER: root
      MYSQL_ROOT_PASSWORD: secret
      MYSQL_ROOT_HOST: localhost
    volumes:
      - mysql_data:/var/lib/mysql
    ports:
      - "3306:3306"
  api:
    build: .
    container_name: spring-api
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - mysql
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/stockdb
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: secret

volumes:
  mysql_data:
    name: mysql_data
